logging:
  level:
    org.springframework.cloud: "debug"

spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bor}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}


negative:
  sleep: ${NEGATIVE_SLEEP:0}