apiVersion: apps/v1
kind: Deployment
metadata:
  name: negative-deployment
  labels:
    app: negative

spec:
  selector:
    matchLabels:
      app: negative
  template:
    metadata:
      labels:
        app: negative
    spec:
      containers:
        - name: negative
          image: munirprog/negative:1.0
          ports:
            - containerPort: 8080
#          env:


---
apiVersion: v1
kind: Service
metadata:
  name: negative-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: negative

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: negative-ingress
#spec:
#  rules:
#    - host: negative.mprog.ag.192.168.49.2.nip.io
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: negative-svc
#                port:
#                  name: http